### ISSUE TITLE
Bitwarden Flatpak Install Shows just a blank screen this morning

### ISSUE THREAD

**Issue by GlenKPeterson** [flathub/com.bitwarden.desktop#165]
See: https://github.com/bitwarden/clients/issues/6732
Someone else had the issue on Fedora, I had it on Ubuntu, both on Flatpak, no other reports of the issue (yet).

**Comment by GlenKPeterson** [comment]
Workaround: I turned off GPU Acceleration in Flatseal and Bitwarden works.  See other issue for details: https://github.com/bitwarden/clients/issues/6732

**Comment by GlenKPeterson** [comment]
Removing the GPU cache folder might be a better solution:
rm -rf ~/.var/app/com.bitwarden.desktop/config/Bitwarden/Partitions/bitwarden/GPUCache
Source:
https://github.com/bitwarden/clients/issues/6732#issuecomment-1785612077

**Comment by leodip** [comment]
I have this issue on Fedora 38, Gnome, Wayland.

I have removed this folder, and it fixed the issue.

`rm -rf ~/.var/app/com.bitwarden.desktop/config/Bitwarden/Partitions/bitwarden/GPUCache`

**Comment by kparal** [comment]
This might be yet another manifestation of this issue:
https://discussion.fedoraproject.org/t/chromium-based-browsers-display-garbled-web-pages-after-mesa-is-updated/83438
https://bugs.chromium.org/p/chromium/issues/detail?id=1442633

**Comment by ghisvail** [comment]
You need to clear the GPU cache:

> I have this issue on Fedora 38, Gnome, Wayland.
> 
> I have removed this folder, and it fixed the issue.
> 
> `rm -rf ~/.var/app/com.bitwarden.desktop/config/Bitwarden/Partitions/bitwarden/GPUCache`

**Comment by kparal** [comment]
@ghisvail Please don't close this issue. Clearing the cache is just a **workaround**, not a solution, and will happen again the next time mesa libraries are updates. Also, only a negligible percentage of users will find this workaround.

This needs a proper solution. What about removing GPU acceleration until the problem is resolved? For Bitwarden it's not needed anyway.

**Comment by ghisvail** [comment]
It's an issue with many Electron apps, not specifically Bitwarden. The issue should be forwarded elsewhere.

> What about removing GPU acceleration until the problem is resolved?

Besides, where do I track the "until the problem is resolved" part? So far, I have got no visibility.

**Comment by kparal** [comment]
> It's an issue with many Electron apps, not specifically Bitwarden. The issue should be forwarded elsewhere.

Yes, I agree, the core issue is not in Bitwarden, and needs to be solved elsewhere. But Bitwarden users are affected, so we need at least some mitigation until the the problem is resolved. If we rely on people finding this ticket and pruning their cache regularly, we'll have 99% of user base leaving annoyed either at Bitwarden or at Flatpak.

I think dropping `--device=dri` from the manifest is a very simple thing to do at this moment, with essentially zero drawbacks.

> Besides, where do I track the "until the problem is resolved" part? So far, I have got no visibility.

I think the proper upstream bug is this one:
https://bugs.chromium.org/p/chromium/issues/detail?id=1442633

It looks like this got fixed a few weeks back, so hopefully this should be resolved once Electron picks up the fixed Chromium version and then Electron is updated in Bitwarden flatpak, if I understand the deps right?
